# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stats.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stats.proto',
  package='stats',
  syntax='proto3',
  serialized_options=b'Z\007.;stats',
  serialized_pb=b'\n\x0bstats.proto\x12\x05stats\"\x1c\n\x0cStatsRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1d\n\rStatsResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2G\n\x0cStatsService\x12\x37\n\x08GetStats\x12\x13.stats.StatsRequest\x1a\x14.stats.StatsResponse\"\x00\x42\tZ\x07.;statsb\x06proto3'
)




_STATSREQUEST = _descriptor.Descriptor(
  name='StatsRequest',
  full_name='stats.StatsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='stats.StatsRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=50,
)


_STATSRESPONSE = _descriptor.Descriptor(
  name='StatsResponse',
  full_name='stats.StatsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='stats.StatsResponse.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=81,
)

DESCRIPTOR.message_types_by_name['StatsRequest'] = _STATSREQUEST
DESCRIPTOR.message_types_by_name['StatsResponse'] = _STATSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StatsRequest = _reflection.GeneratedProtocolMessageType('StatsRequest', (_message.Message,), {
  'DESCRIPTOR' : _STATSREQUEST,
  '__module__' : 'stats_pb2'
  # @@protoc_insertion_point(class_scope:stats.StatsRequest)
  })
_sym_db.RegisterMessage(StatsRequest)

StatsResponse = _reflection.GeneratedProtocolMessageType('StatsResponse', (_message.Message,), {
  'DESCRIPTOR' : _STATSRESPONSE,
  '__module__' : 'stats_pb2'
  # @@protoc_insertion_point(class_scope:stats.StatsResponse)
  })
_sym_db.RegisterMessage(StatsResponse)


DESCRIPTOR._options = None

_STATSSERVICE = _descriptor.ServiceDescriptor(
  name='StatsService',
  full_name='stats.StatsService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=83,
  serialized_end=154,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetStats',
    full_name='stats.StatsService.GetStats',
    index=0,
    containing_service=None,
    input_type=_STATSREQUEST,
    output_type=_STATSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STATSSERVICE)

DESCRIPTOR.services_by_name['StatsService'] = _STATSSERVICE

# @@protoc_insertion_point(module_scope)
